# Generated by Django 5.2.8 on 2025-11-17 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0005_update_default_category_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='currency',
            field=models.CharField(default='INR', max_length=10),
        ),
    ]
